#!/usr/bin/env php
<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

$app = require_once 'app.php';

$console = new Symfony\Component\Console\Application($app['name'], $app['version']);
$console->setDispatcher($app['dispatcher']);

$runAwsCommand = new Majordome\Command\RunAWSCommand($app);
$sendReportCommand = new Majordome\Command\SendReportCommand($app);

$console->add($runAwsCommand);
$console->add($sendReportCommand);

$console->run();
