name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4', '8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php }} environment
      uses: nanasess/setup-php@v4
      with:
        php-version: ${{ matrix.php }}
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Copy example config
      run: cp app/config.php.dist app/config.php

    - name: Install dependencies
      run: make install-dev

    - name: Run tests suite
      run: make test
