name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php }} environment
      uses: nanasess/setup-php@v4
      with:
        php-version: ${{ matrix.php }}
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Copy .env.example
      run: cp .env.example .env

    - name: Install dependencies
      run: make install-dev

    - name: Run tests suite
      run: make test
